mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"

app:
    build: 
      dockerfile: docker/dockerfile
      ports: 
        - "8085:8080"
      links: 
        - mongo